[project]
name = "footScrapper"
version = "1.0.0"
description = "Python command line interface to list upcoming matchs for given team (using allsportsapi.com)"
dependencies = [
  "docopt",
  "dotenv",
  "tzlocal"
]

[tool.ruff]
line-length = 110
